using Microsoft.Extensions.Logging;
using Reminder.Interfaces;
using Reminder.Models;
using System.Text;

namespace Reminder.Services
{
    public class GooglePhotosScheduleAction : ScheduleAction
    {
        private readonly IGooglePhotosReminderDataAccess _dataAccess;
        private readonly ILogger _logger;

        public GooglePhotosScheduleAction(INotificationService emailService, IGooglePhotosReminderDataAccess dataAccess, ILogger<GooglePhotosScheduleAction> logger) : base(emailService)
        {
            _dataAccess = dataAccess;
            _logger = logger;
        }

        public async override Task ExecuteAsync(Schedule schedule)
        {
            foreach (var recipient in schedule.Recipients)
            {
                var sendTo = recipient.Email;
                var startDate = _dataAccess.GetLastSearchStartDate(sendTo);

                var endDate = startDate.AddDays(7);
                var dateRange = $"{startDate:yyyy-MM-dd} to {endDate:yyyy-MM-dd}";

                var body = $@"
                    <!DOCTYPE html>
                    <html>
                    <head>
                        <meta charset='utf-8'>
                    </head>
                    <body style='margin:0;padding:20px;background-color:#f4f6f8;font-family:Segoe UI,Arial,sans-serif;'>

                        <div style='max-width:600px;margin:auto;background-color:white;border-radius:12px;padding:32px;box-shadow:0 2px 8px rgba(0,0,0,0.08);'>

                            <h2 style='margin-top:0;color:#1a73e8;'>
                                📸 Google Photos Cleanup Reminder
                            </h2>

                            <p>
                                Hi {recipient.Name}!
                            </p>

                            <p>
                                You should take a few minutes to clean up some old photos!
                            </p>

                            <h3 style='margin-bottom:8px;'>Step 1: Copy this date range</h3>

                            <div style='background:#f8f9fa;
                                        border:2px solid #1a73e8;
                                        border-radius:8px;
                                        padding:20px;
                                        margin-bottom:24px;
                                        text-align:center;'>
                                <textarea readonly 
                                          rows=""1""
                                          style='width: 100%;
                                                 max-width: 100%;
                                                 background: transparent;
                                                 border: none;
                                                 outline: none;
                                                 resize: none;
                                                 text-align: center;
                                                 font-size:14px;
                                                 font-family:Consolas,Courier New,monospace;
                                                 font-weight:600;
                                                 color:#202124;
                                                 user-select:all;
                                                 -webkit-user-select:all;'>
                                    {dateRange}
                                </textarea>
                            </div>

                            <h3>Step 2</h3>
                            <p>Open Google Photos</p>

                            <h3>Step 3</h3>
                            <p>Click the Search box.</p>

                            <h3>Step 4</h3>
                            <p>Paste the date range from Step 1.</p>

                            <hr style='border:none;border-top:1px solid #ddd;margin:32px 0;'>

                            <p style='font-size:12px;color:#666;margin:0;'>
                                Generated by your husband who loves you.
                            </p>

                        </div>

                    </body>
                    </html>";

                _logger.LogInformation("Sending email to {recipient}", recipient.Email);
                await _emailService.SendAsync(recipient, schedule?.Name ?? "Google Photos Reminder Default", body);

                _logger.LogInformation("Saving reminder to datbase");
                _dataAccess.SaveReminder(sendTo, body, startDate, startDate.AddDays(7));
            }
        }
    }
}
